;; -*- mode: emacs-lisp -*-
(source gnu)
(source "elpa" "http://tromey.com/elpa/")
(source melpa-stable)

(depends-on "coffee-mode")
(depends-on "color-theme-sanityinc-solarized")
(depends-on "solarized-theme")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "ido-ubiquitous")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "org")
(depends-on "php-mode")
(depends-on "s")
(depends-on "shut-up")
(depends-on "smartparens")
(depends-on "web-mode")
(depends-on "yaml-mode")
(depends-on "zencoding-mode")
(depends-on "projectile")
(depends-on "projectile-rails")
(depends-on "scss-mode")
(depends-on "ace-window")
(depends-on "rbenv")
(depends-on "robe")
(depends-on "rspec-mode")
(depends-on "rubocop")
(depends-on "inf-ruby")
(depends-on "editorconfig")
(depends-on "dockerfile-mode")
(depends-on "yasnippet")
