(source gnu)
(source marmalade)
(source "elpa" "http://tromey.com/elpa/")
(source melpa)

(depends-on "cask")
(depends-on "coffee-mode")
(depends-on "color-theme-sanityinc-solarized")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "ido-ubiquitous")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "org")
(depends-on "org-present")
(depends-on "pallet")
(depends-on "php-mode")
(depends-on "s")
(depends-on "smartparens")
(depends-on "web-mode")
(depends-on "yaml-mode")
(depends-on "zencoding-mode")